import type { Mentor, Testimonial, PricingPlan, Session, ProgressReport, Earnings } from './types';

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'Anjali Sharma',
    location: 'Mumbai, IN',
    quote: 'Finding the right mentor was so easy with MentorLink. My confidence in Math has skyrocketed!',
    rating: 5,
    imageId: 'testimonial-1',
  },
  {
    id: 2,
    name: 'Rohan Mehta',
    location: 'Bangalore, IN',
    quote: 'The flexibility of scheduling and the quality of mentors are top-notch. I actually look forward to my sessions.',
    rating: 5,
    imageId: 'testimonial-2',
  },
  {
    id: 3,
    name: 'Priya Das',
    location: 'Kolkata, IN',
    quote: 'An amazing platform. The community hub option is a game-changer for connecting with other students.',
    rating: 5,
    imageId: 'testimonial-3',
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'basic',
    title: 'Basic',
    description: 'For supplemental learning.',
    price: 1500,
    features: [
      '10 sessions per month',
      'Access to one subject',
      'Email support',
      'Basic progress tracking',
    ],
  },
  {
    id: 'standard',
    title: 'Standard',
    description: 'Our most popular plan.',
    price: 5000,
    features: [
      '20 sessions per month',
      'Access to all subjects',
      'Priority support',
      'Detailed progress reports',
      'College prep guidance',
    ],
    isPopular: true,
  },
  {
    id: 'premium',
    title: 'Premium',
    description: 'For comprehensive support.',
    price: 10000,
    features: [
      'Unlimited sessions per month',
      'Access to all subjects',
      'Dedicated support manager',
      'Personalized learning plans',
      'College prep guidance',
    ],
  },
];

export const mentors: Mentor[] = [
    {
      id: '1',
      name: 'Aditi Rao',
      subjects: ['Math', 'Physics'],
      gradeLevels: ['9th', '10th'],
      rating: 4.9,
      reviewCount: 120,
      experience: '5+ years',
      location: 'Delhi',
      language: 'English, Hindi',
      price: 800,
      isVerified: true,
      imageId: 'mentor-1',
      availability: ['Weekdays', 'Weekends'],
    },
    {
      id: '2',
      name: 'Vikram Singh',
      subjects: ['Chemistry', 'Biology'],
      gradeLevels: ['11th', '12th'],
      rating: 4.8,
      reviewCount: 95,
      experience: '7 years',
      location: 'Bangalore',
      language: 'English',
      price: 1000,
      isVerified: true,
      imageId: 'mentor-2',
      availability: ['Weekdays'],
    },
    {
      id: '3',
      name: 'Nisha Patel',
      subjects: ['English', 'History'],
      gradeLevels: ['6th', '7th', '8th'],
      rating: 4.9,
      reviewCount: 150,
      experience: '8 years',
      location: 'Mumbai',
      language: 'English, Gujarati',
      price: 700,
      isVerified: true,
      imageId: 'mentor-3',
      availability: ['Weekends'],
    },
    {
      id: '4',
      name: 'Arjun Verma',
      subjects: ['Computer Science'],
      gradeLevels: ['10th', '11th', '12th'],
      rating: 5.0,
      reviewCount: 200,
      experience: '10 years',
      location: 'Hyderabad',
      language: 'English, Telugu',
      price: 1200,
      isVerified: true,
      imageId: 'mentor-4',
      availability: ['Weekdays', 'Weekends'],
    },
    {
      id: '5',
      name: 'Sneha Reddy',
      subjects: ['Social Studies', 'Geography'],
      gradeLevels: ['6th', '7th'],
      rating: 4.7,
      reviewCount: 80,
      experience: '4 years',
      location: 'Pune',
      language: 'English, Marathi',
      price: 600,
      isVerified: false,
      imageId: 'mentor-5',
      availability: ['Weekdays'],
    },
    {
      id: '6',
      name: 'Karan Gupta',
      subjects: ['Economics', 'Business Studies'],
      gradeLevels: ['11th', '12th'],
      rating: 4.8,
      reviewCount: 110,
      experience: '6 years',
      location: 'Delhi',
      language: 'English, Hindi',
      price: 900,
      isVerified: true,
      imageId: 'mentor-6',
      availability: ['Weekends'],
    },
  ];
  
export const studentSessions: Session[] = [
  { id: '1', mentorName: 'Aditi Rao', date: '2023-10-15', subject: 'Math', status: 'Completed' },
  { id: '2', mentorName: 'Vikram Singh', date: '2023-10-18', subject: 'Chemistry', status: 'Completed' },
  { id: '3', mentorName: 'Aditi Rao', date: '2023-11-01', subject: 'Math', status: 'Upcoming' },
  { id: '4', mentorName: 'Nisha Patel', date: '2023-09-20', subject: 'English', status: 'Cancelled' },
  { id: '5', mentorName: 'Aditi Rao', date: '2023-11-05', subject: 'Physics', status: 'Upcoming' },
];

export const progressReports: ProgressReport[] = [
  { month: 'Jan', Math: 65, Science: 70, English: 75 },
  { month: 'Feb', Math: 68, Science: 72, English: 78 },
  { month: 'Mar', Math: 75, Science: 75, English: 80 },
  { month: 'Apr', Math: 80, Science: 82, English: 85 },
  { month: 'May', Math: 82, Science: 85, English: 88 },
  { month: 'Jun', Math: 88, Science: 90, English: 92 },
];
  
export const mentorEarnings: Earnings[] = [
    { month: "Jan", amount: 25000 },
    { month: "Feb", amount: 28000 },
    { month: "Mar", amount: 32000 },
    { month: "Apr", amount: 30000 },
    { month: "May", amount: 35000 },
    { month: "Jun", amount: 40000 },
  ];

    
